Repository Ecodenl/Woningdossier, pull requests merged in 2022-11, with the labels that each got.

#1175 Feature/heat pump/action plan mapping
  app/Helpers/Cooperation/Tool/HighEfficiencyBoilerHelper.php
  app/Services/UserActionPlanAdviceService.php
Labels: enhancement

#1174 Feature/heat pump/exception fix
  app/Calculations/HeatPump.php
Labels: bugfix

#1176 Feature/heat pump/savings fix
  app/Calculations/HeatPump.php
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
  app/Helpers/DataTypes/Caster.php
  app/Helpers/NumberFormatter.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  database/migrations/2022_09_02_163615_create_tool_calculation_results_table.php
  database/migrations/2022_11_01_135818_add_data_type_column_to_tool_calculation_results_table.php
  database/seeds/ToolCalculationResultsTableSeeder.php
Labels: bugfix

#1177 Change conditional logic to fix flawed assumption
  app/Services/ConditionService.php
Labels: bugfix

#1178 Map all steps of heating
  app/Helpers/ToolQuestionHelper.php
Labels: enhancement

#1181 Feature/heat pump/interest complexity calc logic
  app/Helpers/ToolQuestionHelper.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Form.php
  app/Policies/SubStepPolicy.php
  database/seeds/SubSteppablesTableSeeder.php
  resources/views/cooperation/sub-step-templates/template-summary/show.blade.php
Labels: enhancement

#1180 Feature/heat pump/csv struct
  app/Jobs/GenerateTotalReport.php
  app/Services/ContentStructureService.php
  app/Services/DumpService.php
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/clickables.css
Labels: bugfix

#1182 Feature/heat pump/pdf fix
  resources/views/cooperation/pdf/user-report/parts/step-summary.blade.php
Labels: bugfix

#1183 Feature/heat pump/map desired power
  app/Calculations/HeatPump.php
  app/Helpers/ToolQuestionHelper.php
  app/Jobs/MapQuickScanSituationToExpert.php
Labels: enhancement

#1184 Show label on calculations
  app/Helpers/ToolHelper.php
Labels: enhancement

#1190 Map desired power differently
  app/Jobs/MapQuickScanSituationToExpert.php
Labels: enhancement

#1194 Feature/heat pump/alert color
  app/Http/Livewire/Cooperation/Frontend/Layouts/Parts/Alerts.php
Labels: enhancement

#1196 Feature/heat pump/expert map fix
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Services/Scans/ScanFlowService.php
  database/seeders/ToolQuestionsTableSeeder.php
Labels: bugfix

#1195 Feature/heat pump/source select fix
  public/css/frontend/app.css
  public/js/app.js
  public/mix-manifest.json
  resources/js/alpine-scripts/source-select.js
Labels: bugfix

#1201 Feature/heat pump/pdf calculation formatting
  app/Http/Controllers/Cooperation/Pdf/UserReportController.php
  app/Jobs/PdfReport.php
Labels: enhancement

#1199 Feature/heat pump/polyfill fix
  package-lock.json
  package.json
  public/js/app.js
  public/mix-manifest.json
  resources/js/alpine-scripts/draggables.js
Labels: bugfix

#1200 Feature/heat pump/building not set fix
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Buttons.php
  app/Http/Middleware/ChecksConditionsForSubSteps.php
  app/Policies/SubStepPolicy.php
  resources/views/cooperation/sub-step-templates/template-summary/show.blade.php
Labels: bugfix

#1154 Feature/file uploader
  app/Helpers/MediaHelper.php
  app/Http/Controllers/Cooperation/Admin/Cooperation/CooperationAdmin/SettingsController.php
  app/Http/Controllers/Cooperation/Auth/RegisterController.php
  app/Http/Controllers/Cooperation/Frontend/Tool/QuickScan/MyPlanController.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/MyPlan/Uploader.php
  app/Models/Building.php
  app/Models/Cooperation.php
  app/Models/Media.php
  app/Policies/MediaPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Traits/HasMedia.php
  composer.json
  composer.lock
  config/hoomdossier.php
  config/livewire.php
  config/mediable.php
  database/migrations/2022_10_21_110448_add_custom_properties_column_to_media_table.php
  docker/nginx/default.conf
  docker/php.dockerfile
  docker/php.ini
  public/css/admin/app.css
  public/css/frontend/app.css
  public/icons/document.svg
  public/icons/trash-can-red.svg
  public/icons/trash-can.svg
  public/js/app.js
  public/mix-manifest.json
  resources/css/frontend/components/items.css
  resources/css/shared/components/icons.css
  resources/icons/document.svg
  resources/icons/trash-can-red.svg
  resources/icons/trash-can.svg
  resources/js/alpine-scripts/modal.js
  resources/js/bootstrap.js
  resources/lang/nl/cooperation/admin/buildings.php
  resources/lang/nl/cooperation/frontend/tool.php
  resources/lang/nl/models/media.php
  resources/lang/nl/validation.php
  resources/views/cooperation/admin/buildings/show.blade.php
  resources/views/cooperation/auth/register.blade.php
  resources/views/cooperation/frontend/layouts/app.blade.php
  resources/views/cooperation/frontend/layouts/parts/navbar.blade.php
  resources/views/cooperation/frontend/layouts/tool.blade.php
  resources/views/cooperation/frontend/tool/quick-scan/my-plan/index.blade.php
  resources/views/cooperation/frontend/tool/quick-scan/my-plan/media.blade.php
  resources/views/livewire/cooperation/frontend/tool/quick-scan/my-plan/download-pdf.blade.php
  resources/views/livewire/cooperation/frontend/tool/quick-scan/my-plan/uploader.blade.php
  routes/web.php
  storage/app/.gitignore
Labels: enhancement, awaiting approval

#1210 Feature/heat pump/element fix
  database/seeders/ElementsValuesTableSeeder.php
Labels: bugfix

#1209 Feature/heat pump/force desired power
  app/Calculations/HeatPump.php
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
Labels: bugfix

#1202 Feature/heat pump/comment fix
  resources/views/cooperation/tool-question-type-templates/textarea-popup/show.blade.php
Labels: bugfix

#1213 Feature/heat pump/init check
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  resources/views/cooperation/tool-question-type-templates/dropdown/show.blade.php
  resources/views/cooperation/tool-question-type-templates/multi-dropdown/show.blade.php
Labels: enhancement

#1188 Feature/shift/laravel UI to fortify
  app/Actions/Fortify/CreateNewUser.php
  app/Actions/Fortify/PasswordValidationRules.php
  app/Actions/Fortify/ResetUserPassword.php
  app/Http/Controllers/Cooperation/Admin/Auth/LoginController.php
  app/Http/Controllers/Cooperation/Auth/AuthenticatedSessionController.php
  app/Http/Controllers/Cooperation/Auth/ForgotPasswordController.php
  app/Http/Controllers/Cooperation/Auth/LoginController.php
  app/Http/Controllers/Cooperation/Auth/PasswordResetLinkController.php
  app/Http/Controllers/Cooperation/Auth/RegisterController.php
  app/Http/Controllers/Cooperation/Auth/RegisteredUserController.php
  app/Http/Controllers/Cooperation/Auth/ResetPasswordController.php
  app/Http/Controllers/Cooperation/Auth/VerificationController.php
  app/Http/Controllers/Cooperation/RecoverOldEmailController.php
  app/Http/Requests/RegisterFormRequest.php
  app/Providers/FortifyServiceProvider.php
  app/Responses/LoginResponse.php
  app/Responses/LogoutResponse.php
  app/Responses/PasswordResetResponse.php
  app/Responses/RegisterResponse.php
  app/Rules/HouseNumberExtension.php
  app/Services/UserService.php
  composer.lock
  config/app.php
  config/fortify.php
  database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
  resources/lang/nl.json
  resources/lang/nl/auth.php
  resources/lang/nl/passwords.php
  resources/views/cooperation/auth/passwords/reset/show.blade.php
  resources/views/cooperation/auth/verify.blade.php
  resources/views/cooperation/mail/user/created/text.blade.php
  resources/views/cooperation/mail/user/created/view.blade.php
  resources/views/cooperation/mail/user/password-reset-request/text.blade.php
  resources/views/cooperation/mail/user/password-reset-request/view.blade.php
  routes/web.php
Labels: enhancement

#1214 Feature/heat pump/string checks
  database/seeders/ToolQuestionsTableSeeder.php
Labels: bugfix

#1218 Feature/heat pump/fix map
  app/Calculations/HeatPump.php
  app/Deprecation/ToolHelper.php
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
  app/Jobs/MapQuickScanSituationToExpert.php
Labels: bugfix

#1226 For the rare building types without a generic example building.
  app/Services/ExampleBuildingService.php
Labels: bugfix

#1225 Correct build year
  app/Services/AddressService.php
Labels: bugfix

#1227 More logging
  app/Providers/RouteServiceProvider.php
  app/Providers/WoningdossierServiceProvider.php
  resources/views/cooperation/frontend/layouts/app.blade.php
  resources/views/cooperation/frontend/layouts/parts/logo.blade.php
Labels: enhancement

#1232 Exception fix
  app/Jobs/MapQuickScanSituationToExpert.php
Labels: bugfix
