Repository Ecodenl/Woningdossier, pull requests merged in 2022-10, with the labels that each got.

#1118 Minor tweaks & cleanup
  app/Helpers/SubStepHelper.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Buttons.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Form.php
  app/Services/DiscordNotifier.php
  app/Services/Scans/ScanFlowService.php
  database/seeds/AlertsTableSeeder.php
  resources/views/cooperation/frontend/tool/quick-scan/index.blade.php
  resources/views/livewire/cooperation/frontend/tool/quick-scan/buttons.blade.php
Labels: enhancement, bugfix

#1126 Only uncomplete (sub) steps related to the current scan
  app/Models/SubStep.php
  app/Models/SubSteppable.php
  app/Services/Scans/ScanFlowService.php
Labels: bugfix

#1125 Feature/heat pump/my plan fixes
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/MyPlan/Form.php
  public/js/app.js
  public/mix-manifest.json
  resources/js/alpine-scripts/draggables.js
  resources/views/livewire/cooperation/frontend/tool/quick-scan/my-plan/form.blade.php
Labels: enhancement, bugfix

#1124 Feature/heat pump/heat pump unit/size alert
  database/seeds/AlertsTableSeeder.php
Labels: enhancement

#1123 Feature/heat pump/advice category conditional/hr boiler alert
  app/Helpers/Conditions/Evaluators/AdviceCategory.php
  app/Helpers/Conditions/Evaluators/BuildingType.php
  app/Helpers/Conditions/Evaluators/InsulationScore.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/MyPlan/Form.php
  app/Models/UserActionPlanAdvice.php
  database/seeds/AlertsTableSeeder.php
  public/css/frontend/app.css
  public/js/app.js
  public/mix-manifest.json
  resources/js/alpine-scripts/draggables.js
Labels: enhancement, bugfix

#1121 Feature/heat pump/fifty degrees logic
  database/seeds/SubSteppablesTableSeeder.php
Labels: enhancement

#1120 Feature/heat pump/sun boiler calc fix
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/MyPlan/Form.php
Labels: bugfix

#1128 Feature/heat pump/field moving
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolCalculationResultsTableSeeder.php
Labels: enhancement

#1134 Feature/heat pump/water label
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolLabelsTableSeeder.php
Labels: enhancement

#1136 Feature/heat pump/empty step
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
Labels: bugfix

#1135 Feature/heat pump/recalculate notification
  app/Console/Commands/Tool/RecalculateForUser.php
  app/Http/Controllers/Cooperation/Frontend/Tool/QuickScan/MyPlanController.php
  app/Http/Livewire/Cooperation/Frontend/Layouts/Parts/Notifications.php
  app/Http/Middleware/DuplicateDataForBuilding.php
  app/Jobs/CloneOpposingInputSource.php
  app/Jobs/RecalculateStepForUser.php
  app/Models/Notification.php
  app/Providers/AppServiceProvider.php
  app/Services/Models/NotificationService.php
  database/migrations/2020_11_26_154044_create_notifications_table.php
  database/migrations/2022_10_13_140902_add_active_count_column_to_notifications_table.php
  resources/views/cooperation/frontend/tool/quick-scan/index.blade.php
  resources/views/cooperation/frontend/tool/quick-scan/my-plan/index.blade.php
Labels: enhancement, bugfix

#1139 Bugfixes in calculator, remove obsolete code
  app/Calculations/HeatPump.php
  app/Helpers/DataTypes/Caster.php
  app/Helpers/NumberFormatter.php
  app/Helpers/QuestionValues/readme.md
  app/Helpers/ToolHelper.php
  app/Helpers/ToolQuestionHelper.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Services/DumpService.php
  app/Traits/HasDynamicAnswers.php
  database/seeds/ToolQuestionsTableSeeder.php
Labels: enhancement, bugfix

#1138 Feature/heat pump/example building csv
  app/Helpers/ExampleBuildingHelper.php
  app/Helpers/ToolHelper.php
  app/Http/Controllers/Cooperation/Admin/ExampleBuildingController.php
  app/Http/Livewire/Cooperation/Admin/ExampleBuildings/CsvExport.php
  app/Http/Livewire/Cooperation/Admin/ExampleBuildings/Form.php
  app/Http/Requests/Cooperation/Admin/ExampleBuildingRequest.php
  app/Jobs/GenerateExampleBuildingCsv.php
  app/Services/ContentStructureService.php
  app/Services/ExampleBuildingService2.php
  resources/views/cooperation/admin/example-buildings/components/building-type.blade.php
  resources/views/cooperation/admin/example-buildings/components/content-table.blade.php
  resources/views/cooperation/admin/example-buildings/components/contents.blade.php
  resources/views/cooperation/admin/example-buildings/components/cooperation.blade.php
  resources/views/cooperation/admin/example-buildings/components/is_default.blade.php
  resources/views/cooperation/admin/example-buildings/components/names.blade.php
  resources/views/cooperation/admin/example-buildings/components/order.blade.php
  resources/views/cooperation/admin/example-buildings/create.blade.php
  resources/views/cooperation/admin/example-buildings/edit.blade.php
  resources/views/cooperation/admin/example-buildings/parts/row-data.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/checkbox-icon/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/dropdown/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/multi-dropdown/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/radio-icon-small/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/radio-icon/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/radio/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/rating-slider/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/slider/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/text/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/textarea-popup/show.blade.php
  resources/views/cooperation/admin/example-buildings/tool-question-type-templates/textarea/show.blade.php
  resources/views/livewire/cooperation/admin/example-buildings/csv-export.blade.php
Labels: enhancement, bugfix

#1133 Remove old views
  resources/views/cooperation/tool/heat-pump/index.blade.php
  resources/views/cooperation/tool/heater/index.blade.php
  resources/views/cooperation/tool/hr-boiler/index.blade.php
Labels: enhancement

#1148 Feature/heat pump/example building question fixes
  app/Helpers/ExampleBuildingHelper.php
  resources/views/cooperation/admin/example-buildings/components/content-table.blade.php
Labels: bugfix

#1150 Feature/heat pump/short mapping
  app/Helpers/ToolQuestionHelper.php
Labels: enhancement

#1153 Feature/heat pump/example building bugfixes
  database/seeds/ToolQuestionsTableSeeder.php
Labels: bugfix

#1144 Feature/heat pump/next url bug
  app/Http/Controllers/Cooperation/Tool/QuestionnaireController.php
  app/Models/Scan.php
  app/Services/Scans/ScanFlowService.php
  resources/views/cooperation/sub-step-templates/template-summary/show.blade.php
  resources/views/livewire/cooperation/frontend/tool/quick-scan/buttons.blade.php
Labels: bugfix

#1149 Feature/heat pump/example building substep fix
  app/Http/Livewire/Cooperation/Admin/ExampleBuildings/Form.php
  resources/views/cooperation/admin/example-buildings/components/content-table.blade.php
  resources/views/livewire/cooperation/admin/example-buildings/form.blade.php
Labels: bugfix

#1146 Fix master input source not saving when completing questionnaire
  app/Http/Controllers/Cooperation/Tool/QuestionnaireController.php
  app/Models/User.php
  app/Services/Models/QuestionnaireService.php
  app/Services/QuestionnaireService.php
Labels: bugfix

#1155 Feature/heat pump/fix desired power
  app/Helpers/DataTypes/Caster.php
  app/Helpers/NumberFormatter.php
  app/Traits/HasDynamicAnswers.php
Labels: bugfix

#1141 Feature/heat pump/expert scan considerable logic
  app/Calculations/Calculator.php
  app/Calculations/FloorInsulation.php
  app/Calculations/HeatPump.php
  app/Calculations/Heater.php
  app/Calculations/HighEfficiencyBoiler.php
  app/Calculations/WallInsulation.php
  app/Console/Commands/Upgrade/HeatPump/ExampleBuildingContentRestructure.php
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
  app/Helpers/Conditions/ConditionEvaluator.php
  app/Helpers/Conditions/Evaluators/HrBoilerAdvice.php
  app/Helpers/Conditions/Evaluators/InsulationAdvice.php
  app/Helpers/Conditions/Evaluators/InsulationScore.php
  app/Helpers/Conditions/Evaluators/SunBoilerPerformance.php
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
  app/Helpers/Cooperation/Tool/HeaterHelper.php
  app/Helpers/Cooperation/Tool/HighEfficiencyBoilerHelper.php
  app/Helpers/Cooperation/Tool/ToolHelper.php
  app/Helpers/ExampleBuildingHelper.php
  app/Helpers/HighEfficiencyBoilerCalculator.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Models/Alert.php
  app/Models/MeasureApplication.php
  app/Models/ToolCalculationResult.php
  app/Models/ToolQuestion.php
  app/Services/ConditionService.php
  app/Services/DumpService.php
  app/Services/ToolQuestionService.php
  app/Traits/HasDynamicAnswers.php
  app/Traits/RetrievesAnswers.php
  database/seeds/AlertsTableSeeder.php
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolLabelsTableSeeder.php
  database/seeds/ToolQuestionsTableSeeder.php
  docs/code-business-logic/condition-evaluator.md
  tests/Unit/app/Helpers/Conditions/ConditionEvaluatorTest.php
Labels: enhancement

#1147 Feature/heat pump/example building checks
  app/Models/Building.php
  app/Models/ExampleBuilding.php
  app/Traits/ToolSettingTrait.php
Labels: enhancement

#1156 Feature/heat pump/alert changes
  database/seeds/AlertsTableSeeder.php
Labels: enhancement

#1158 Feature/heat pump/pdf update
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
  app/Http/Controllers/Cooperation/Pdf/UserReportController.php
  app/Jobs/PdfReport.php
  app/Services/DumpService.php
  app/Traits/HasDynamicAnswers.php
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolQuestionsTableSeeder.php
  resources/lang/nl/pdf/user-report.php
  resources/views/cooperation/pdf/user-report/index.blade.php
  resources/views/cooperation/pdf/user-report/parts/measure-page.blade.php
  resources/views/cooperation/pdf/user-report/parts/measure-page/filled-in-data-new.blade.php
  resources/views/cooperation/pdf/user-report/parts/measure-page/step-intro.blade.php
Labels: enhancement

#1164 Feature/heat pump/category mapping
  app/Helpers/Conditions/Evaluators/AdviceCategory.php
  app/Helpers/Conditions/Evaluators/HasCompletedStep.php
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
  app/Helpers/Cooperation/Tool/HeaterHelper.php
  app/Helpers/Cooperation/Tool/HighEfficiencyBoilerHelper.php
  app/Helpers/Cooperation/Tool/ToolHelper.php
  app/Helpers/HighEfficiencyBoilerCalculator.php
  app/Services/ConditionService.php
  app/Services/UserActionPlanAdviceService.php
Labels: enhancement

#1165 Feature/heat pump/csv fixes
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
  app/Helpers/ExampleBuildingHelper.php
  app/Helpers/QuestionValues/SpecificExampleBuilding.php
  app/Helpers/ToolHelper.php
  app/Models/Building.php
  app/Services/DumpService.php
  app/Traits/HasDynamicAnswers.php
  app/Traits/RetrievesAnswers.php
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolCalculationResultsTableSeeder.php
  database/seeds/ToolQuestionsTableSeeder.php
Labels: bugfix

#1160 Logging to find out why the damn cooperation isn't set
  resources/views/cooperation/frontend/layouts/app.blade.php
Labels: bugfix

#1163 Use dynamic answer instead of habit
  app/Calculations/Heater.php
  app/Helpers/HighEfficiencyBoilerCalculator.php
  app/Helpers/KeyFigures/Heater/KeyFigures.php
Labels: bugfix

#1167 Feature/heat pump/condition step completion fix
  app/Helpers/StepHelper.php
  app/Helpers/SubStepHelper.php
  app/Helpers/ToolQuestionHelper.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Form.php
  app/Services/Scans/ScanFlowService.php
Labels: bugfix

#1169 Als gewenst vermogen wp hoger is dan indicatief vermogen is dekkingsg…
  app/Calculations/HeatPump.php
Labels: bugfix

#1170 Feature/heat pump/calc fix
  app/Helpers/Cooperation/Tool/HighEfficiencyBoilerHelper.php
Labels: bugfix

#1172 Feature/heat pump/pdf fix
  app/Helpers/StepHelper.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  resources/views/cooperation/pdf/user-report/index.blade.php
Labels: enhancement, bugfix

#1173 Wrong way around :facepalm:
  app/Calculations/HeatPump.php
Labels: bugfix
