Repository Ecodenl/Woningdossier, pull requests merged in 2022-12, with the labels that each got.

#1216 Feature/heat pump/water calc/single option
  app/Helpers/Conditions/Evaluators/HasMaximumAnswers.php
  app/Jobs/MapQuickScanSituationToExpert.php
  app/Services/ToolQuestionService.php
  database/seeders/ToolQuestionsTableSeeder.php
Labels: enhancement

#1250 Status might not be set
  app/Jobs/GenerateTotalReport.php
  app/Models/Status.php
  app/Services/DumpService.php
Labels: bugfix

#1249 Allow observing users to acces my plan
  app/Http/Controllers/Cooperation/Frontend/Tool/QuickScan/MyPlanController.php
  routes/web.php
Labels: enhancement

#1219 Added dynamic cooperation name.
  resources/lang/nl/conversation-requests.php
  resources/views/cooperation/auth/register.blade.php
Labels: accepted

#1246 Appointment date format to Y-m-d H:i
  app/Services/CsvService.php
  app/Services/DumpService.php
  resources/views/cooperation/admin/buildings/show.blade.php
  resources/views/cooperation/admin/coach/buildings/index.blade.php
  resources/views/cooperation/admin/cooperation/coaches/show.blade.php
Labels: accepted

#1234 Cache can't hold null
  app/Helpers/Cache/BaseCache.php
  app/Traits/HasShortTrait.php
Labels: enhancement

#1235 Optimize validation preparation
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  database/seeders/ToolQuestionsTableSeeder.php
Labels: enhancement, accepted

#1236 Optimize boot
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Models/Building.php
Labels: enhancement

#1237 Eager load roles
  app/Listeners/SuccessFullLoginListener.php
  app/Models/User.php
Labels: enhancement, accepted

#1238 Feature/hold custom evaluators
  app/Helpers/Conditions/ConditionEvaluator.php
  app/Helpers/Conditions/Evaluators/AdviceCategory.php
  app/Helpers/Conditions/Evaluators/BuildingType.php
  app/Helpers/Conditions/Evaluators/HasCompletedStep.php
  app/Helpers/Conditions/Evaluators/HrBoilerAdvice.php
  app/Helpers/Conditions/Evaluators/InsulationAdvice.php
  app/Helpers/Conditions/Evaluators/InsulationScore.php
  app/Helpers/Conditions/Evaluators/ShouldEvaluate.php
  app/Helpers/Conditions/Evaluators/SpecificExampleBuilding.php
  app/Helpers/Conditions/Evaluators/SunBoilerPerformance.php
  docs/code-business-logic/condition-evaluator.md
Labels: enhancement

#1247 Update legacy code to be complient with Laravel 8 (exception to throwable)
  app/Jobs/CloneOpposingInputSource.php
  app/Jobs/GenerateCustomQuestionnaireReport.php
  app/Jobs/GenerateExampleBuildingCsv.php
  app/Jobs/GenerateMeasureReport.php
  app/Jobs/GenerateTotalReport.php
  app/Jobs/PdfReport.php
  app/Jobs/RecalculateStepForUser.php
  app/Jobs/SendUnreadMessageCountEmail.php
Labels: awaiting approval, bugfix

#1248 Feature/call sentry on failed
  app/Jobs/CloneOpposingInputSource.php
  app/Jobs/GenerateCustomQuestionnaireReport.php
  app/Jobs/GenerateExampleBuildingCsv.php
  app/Jobs/GenerateMeasureReport.php
  app/Jobs/GenerateTotalReport.php
  app/Jobs/PdfReport.php
  app/Jobs/RecalculateStepForUser.php
  app/Jobs/SendUnreadMessageCountEmail.php
Labels: awaiting approval, bugfix

#1244 It's possible that new contents aren't set either
  app/Jobs/ApplyExampleBuildingForChanges.php
Labels: awaiting approval, bugfix

#1230 Feature/fix calc
  app/Calculations/Calculator.php
  app/Calculations/HeatPump.php
  app/Calculations/HighEfficiencyBoiler.php
  app/Calculations/Ventilation.php
  app/Helpers/Calculator.php
  app/Helpers/HighEfficiencyBoilerCalculator.php
  app/Models/Building.php
  app/Traits/HasDynamicAnswers.php
Labels: enhancement, awaiting approval

#1257 Collection might not be set
  app/Calculations/Calculator.php
Labels: bugfix

#1189 Feature/shift/livewire upgrade
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/MyPlan/Comments.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/MyPlan/Uploader.php
  resources/views/cooperation/frontend/tool/quick-scan/my-plan/media.blade.php
Labels: enhancement

#1256 feature/livewire-tmp-exception
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/MyPlan/Uploader.php
  app/Rules/MaxFilenameLength.php
  config/livewire.php
  resources/lang/nl/validation.php
  resources/views/livewire/cooperation/frontend/tool/quick-scan/my-plan/uploader.blade.php
Labels: awaiting approval, bugfix

#1243 Not "de" but "het"
  resources/lang/nl/validation.php
Labels: enhancement, awaiting approval

#1259 Sentry Logging
  app/Providers/EventServiceProvider.php
Labels: enhancement

#1220 Calculation systematics
  app/Calculations/HeatPump.php
  app/Calculations/Heating.php
  app/Helpers/Kengetallen.php
  app/Helpers/KeyFigures/Heater/KeyFigures.php
  database/seeders/HeatPumpCharacteristicsTableSeeder.php
Labels: enhancement

#1253 Seed placeholder icon
  database/seeders/ToolQuestionsTableSeeder.php
Labels: enhancement

#1242 Move comments in PDF
  app/Http/Controllers/Cooperation/Pdf/UserReportController.php
  app/Jobs/PdfReport.php
  resources/views/cooperation/pdf/user-report/index.blade.php
  resources/views/cooperation/pdf/user-report/parts/measure-page.blade.php
  resources/views/cooperation/pdf/user-report/parts/measure-page/comments.blade.php
  resources/views/cooperation/pdf/user-report/parts/measure-page/filled-in-data-new.blade.php
  resources/views/cooperation/pdf/user-report/steps/general-data-page-2.blade.php
Labels: enhancement, awaiting approval

#1260 Feature/more exception fixes
  app/Providers/AppServiceProvider.php
  app/Providers/EventServiceProvider.php
  config/livewire.php
Labels: bugfix

#1231 Add alert colors to safelist
  public/css/frontend/app.css
  public/js/app.js
  public/mix-manifest.json
  tailwind.config.js
Labels: bugfix

#1262 Can't be null
  app/Services/DiscordNotifier.php
Labels: bugfix

#1252 Feature/lite scan/explain calculations
  app/Http/Controllers/Cooperation/Frontend/Tool/SimpleScan/MyPlanController.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/CalculationsTable.php
  app/Models/Building.php
  app/Services/BuildingService.php
  resources/lang/nl/cooperation/frontend/tool.php
  resources/views/cooperation/frontend/layouts/components/modal.blade.php
  resources/views/cooperation/frontend/tool/simple-scan/my-plan/index.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/calculations-table.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/download-pdf.blade.php
Labels: enhancement

#1266 Feature/lite scan/large measures
  app/Console/Commands/Upgrade/LiteScan/DoUpgrade.php
  app/Console/Commands/Upgrade/LiteScan/UpdateCooperationMeasures.php
  app/Helpers/Models/CooperationMeasureApplicationHelper.php
  app/Helpers/SubStepHelper.php
  app/Http/Controllers/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationController.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/CustomChanges.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/Form.php
  app/Jobs/HandleCooperationMeasureApplicationDeletion.php
  app/Jobs/MoveCooperationMeasureApplicationToCustomMeasureApplications.php
  app/Models/Cooperation.php
  app/Models/CooperationMeasureApplication.php
  app/Models/CooperationScan.php
  app/Models/Scan.php
  app/Models/SubStep.php
  app/Models/UserActionPlanAdvice.php
  app/Observers/CooperationObserver.php
  app/Policies/CooperationMeasureApplicationPolicy.php
  app/Providers/WoningdossierServiceProvider.php
  database/migrations/2021_08_25_112402_create_cooperation_measure_applications_table.php
  database/migrations/2022_12_07_110444_add_columns_to_cooperation_measure_applications_table.php
  database/seeders/CooperationMeasureApplicationsTableSeeder.php
  database/seeders/SubSteppablesTableSeeder.php
  public/css/admin/app.css
  public/mix-manifest.json
  resources/lang/nl/cooperation/admin/shared.php
  resources/lang/nl/livewire/cooperation/frontend/tool/quick-scan/custom-changes.php
  resources/lang/nl/livewire/cooperation/frontend/tool/simple-scan/custom-changes.php
  resources/sass/admin/app.scss
  resources/views/cooperation/admin/cooperation/cooperation-admin/cooperation-measure-applications/create.blade.php
  resources/views/cooperation/admin/cooperation/cooperation-admin/cooperation-measure-applications/edit.blade.php
  resources/views/cooperation/admin/cooperation/cooperation-admin/cooperation-measure-applications/index.blade.php
  resources/views/cooperation/admin/layouts/sidebar-menu.blade.php
  resources/views/cooperation/sub-step-templates/template-custom-changes/show.blade.php
  resources/views/cooperation/sub-step-templates/template-summary/show.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/custom-changes.blade.php
  routes/web.php
Labels: enhancement

#1274 Feature/lite scan/my account fix
  app/Http/ViewComposers/Frontend/Tool/NavbarComposer.php
  app/Models/Scan.php
  resources/views/cooperation/frontend/layouts/parts/navbar.blade.php
Labels: enhancement

#1275 Feature/lite scan/substeppable fix
  resources/views/cooperation/sub-step-templates/template-2-rows-1-top-2-bottom/show.blade.php
  resources/views/cooperation/sub-step-templates/template-2-rows-3-top-1-bottom/show.blade.php
  resources/views/cooperation/sub-step-templates/template-summary/show.blade.php
Labels: bugfix

#1270 Keep existing info from admin
  app/Http/Requests/Cooperation/Admin/SuperAdmin/ToolCalculationResultFormRequest.php
  database/seeders/ToolCalculationResultsTableSeeder.php
Labels: enhancement

#1241 Feature/docker to sail
  .env.example
  composer.json
  composer.lock
  database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
  database/migrations/2019_01_11_145518_private_messages_table_reorder_columns.php
  database/migrations/2019_03_21_143514_add_new_translations_to_language_lines_table.php
  database/migrations/2019_04_02_171202_add_wall_insulation_measure_name_to_language_lines.php
  database/migrations/2019_04_30_151347_change_my_plan_interested_title_translation.php
  database/migrations/2019_05_16_120815_add_input_source_ids_to_existing_private_message_views.php
  database/migrations/2019_05_22_095543_remove_insulated_glazing_indication_for_costs_gas_translation_from_language_lines.php
  database/migrations/2019_05_22_115442_add_cooperation_ids_to_cooperation_id_column_on_model_has_roles_table.php
  database/migrations/2019_06_26_111613_add_two_factor_columns_to_accounts_table.php
  database/migrations/2019_06_26_203248_have_user_for_each_cooperation.php
  database/migrations/2019_07_01_104830_update_building_to_user_account_structure.php
  database/migrations/2019_09_03_112028_add_input_source_id_to_file_storages_table.php
  database/migrations/2019_09_03_150817_add_building_id_to_file_storages_table.php
  database/migrations/2019_10_23_101315_add_sub_steps_to_steps_table.php
  database/migrations/2019_10_28_160907_migrate_old_heat_pump_service_values_to_new_service_values_for_heat_pump_on_service_table.php
  database/migrations/2019_10_30_101852_delete_demand_driven_service_value_from_service_values_table.php
  database/migrations/2019_11_06_094029_copy_general_data_comment_to_usage_step_on_step_comments_table.php
  database/migrations/2019_11_20_094138_add_input_source_ids_to_input_source_column_on_completed_questionnaires_table.php
  database/migrations/2019_12_11_102024_complete_general_data_sub_steps_on_completed_steps_table.php
  database/migrations/2020_01_07_144303_remove_crack_sealing_measure_from_user_action_plan_advices_table_on_step_4.php
  database/migrations/2020_04_14_083454_update_translation_on_translations_table.php
  database/migrations/2020_12_11_111529_drop_column_allow_access_on_private_messages_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/KeyFigureBoilerEfficienciesTableSeeder.php
  database/seeders/MeasureApplicationsTableSeeder.php
  database/seeders/NotificationIntervalsTableSeeder.php
  database/seeders/NotificationTypesTableSeeder.php
  database/seeders/ServiceValuesTableSeeder.php
  database/seeders/UsersTableSeeder.php
  docker-compose.yml
  docker/7.4/Dockerfile
  docker/7.4/php.ini
  docker/7.4/start-container
  docker/7.4/supervisord.conf
  docker/nginx.dockerfile
  docker/nginx/default.conf
  docker/php.dockerfile
  docker/php.ini
  docs/setup/docker.md
  resources/views/cooperation/admin/buildings/show.blade.php
Labels: enhancement

#1224 Much more stable method of disabling inputs on change
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  public/css/admin/app.css
  public/css/admin/datatables/dataTables.bootstrap.min.css
  public/css/frontend/app.css
  public/js/app.js
  public/mix-manifest.json
  resources/css/frontend/components/form.css
  resources/js/alpine-scripts/alpine-select.js
  resources/js/alpine-scripts/source-select.js
  resources/js/bootstrap.js
  resources/views/cooperation/frontend/layouts/components/alpine-select.blade.php
  resources/views/cooperation/tool-question-type-templates/dropdown/show.blade.php
  resources/views/cooperation/tool-question-type-templates/multi-dropdown/show.blade.php
  resources/views/cooperation/tool-question-type-templates/text/show.blade.php
  resources/views/cooperation/tool-question-type-templates/textarea-popup/show.blade.php
  resources/views/cooperation/tool-question-type-templates/textarea/show.blade.php
  resources/views/livewire/cooperation/frontend/tool/expert-scan/form.blade.php
Labels: enhancement, awaiting approval

#1279 Only display text
  resources/views/cooperation/home/index.blade.php
Labels: enhancement

#1281 Weird behaviour due to middleware
  app/Helpers/ExampleBuildingHelper.php
  app/Http/Middleware/ChecksConditionsForSubSteps.php
Labels: enhancement

#1286 Don't allow users to go to another scan if not set
  app/Http/Kernel.php
  app/Http/Middleware/CooperationHasScan.php
  routes/web.php
Labels: enhancement

#1282 feature/lite-scan/complete-related-substeps
  app/Console/Commands/Upgrade/LiteScan/DoUpgrade.php
  app/Console/Commands/Upgrade/LiteScan/TriggerSaveForAllCompletedSubSteps.php
  app/Helpers/Conditions/ConditionEvaluator.php
  app/Helpers/StepHelper.php
  app/Helpers/SubStepHelper.php
  app/Http/Controllers/Cooperation/Tool/ToolController.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/CalculationsTable.php
  app/Jobs/CompleteRelatedSubStep.php
  app/Observers/CompletedSubStepObserver.php
  app/Services/Models/SubStepService.php
  app/Services/Scans/ScanFlowService.php
Labels: enhancement

#1289 Feature/lite scan/calc fix
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
Labels: bugfix

#1285 Append questionnaires to step counter
  app/Http/ViewComposers/Frontend/Tool/SimpleScanComposer.php
  database/seeders/SubSteppablesTableSeeder.php
Labels: enhancement

#1290 feature/lite-scan/my-plan-expert-logic
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/Form.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/form.blade.php
Labels: enhancement

#1284 Set text based on progress
  app/Services/Models/ScanService.php
  resources/lang/nl/home.php
  resources/views/cooperation/home/index.blade.php
Labels: enhancement

#1278 Delete completed step
  app/Console/Commands/Upgrade/LiteScan/DeleteCompletedStep.php
  app/Console/Commands/Upgrade/LiteScan/DoUpgrade.php
Labels: enhancement

#1291 Cleanup
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
Labels: enhancement

#1293 Feature/lite scan/measure fixes
  app/Models/MeasureApplication.php
Labels: bugfix

#1294 Make coach help nullable
  database/seeders/ToolQuestionsTableSeeder.php
Labels: enhancement

#1300 Feature/water calc/logic fix
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
  app/Observers/UserActionPlanAdviceObserver.php
Labels: bugfix

#1298 Feature/lite scan/exception fix
  app/Http/Controllers/Cooperation/Admin/BuildingController.php
  resources/views/cooperation/admin/buildings/show.blade.php
  routes/web.php
Labels: bugfix

#1299 Feature/lite scan/measure applications/extended editability
  app/Console/Commands/Upgrade/LiteScan/GiveCooperationDefaultScans.php
  app/Helpers/Cooperation/Tool/SmallMeasureHelper.php
  app/Http/Controllers/Cooperation/Admin/SuperAdmin/MeasureApplicationController.php
  app/Http/Requests/Cooperation/Admin/SuperAdmin/MeasureApplicationFormRequest.php
  app/Models/MeasureApplication.php
  database/migrations/2014_11_02_050000_create_measure_applications_table.php
  database/migrations/2022_12_19_120942_add_editable_columns_to_measure_applications_table.php
  database/seeders/MeasureApplicationsTableSeeder.php
  resources/lang/nl/cooperation/admin/super-admin/measure-applications.php
  resources/lang/nl/validation.php
  resources/views/cooperation/admin/super-admin/measure-applications/edit.blade.php
Labels: enhancement

#1305 use correct scan routes
  app/Http/Controllers/Cooperation/Admin/ToolController.php
Labels: bugfix

#1301 Feature/lite scan/csv
  app/Console/Commands/Upgrade/LiteScan/DoUpgrade.php
  app/Console/Commands/Upgrade/LiteScan/RemoveActionPlanReport.php
  app/Helpers/ToolHelper.php
  app/Http/Controllers/Cooperation/ConversationRequest/ConversationRequestController.php
  app/Http/Controllers/Cooperation/FileStorageController.php
  app/Jobs/GenerateExampleBuildingCsv.php
  app/Jobs/GenerateMeasureReport.php
  app/Jobs/GenerateToolReport.php
  app/Services/CsvService.php
  app/Services/DumpService.php
  database/migrations/2019_05_09_102112_create_file_storages_table.php
  database/migrations/2019_09_03_140824_drop_content_type_from_file_storages_table.php
  database/seeders/FileTypesTableSeeder.php
  resources/views/cooperation/admin/cooperation/reports/index.blade.php
  resources/views/cooperation/admin/cooperation/reports/parts/file-type-questionnaire-table-row.blade.php
  resources/views/cooperation/conversation-requests/index.blade.php
  resources/views/cooperation/pdf/user-report/steps/ventilation.blade.php
Labels: enhancement, bugfix

#1295 Feature/lite scan/calc explain/new questions
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/CalculationsTable.php
  app/Services/BuildingService.php
  resources/lang/nl/cooperation/frontend/tool.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/calculations-table.blade.php
Labels: enhancement

#1302 Feature/lite scan/calc explain/extra logic
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/CalculationsTable.php
  app/Jobs/ApplyExampleBuildingForChanges.php
  app/Services/Models/BuildingService.php
  app/Services/ToolQuestionService.php
  app/Services/UserService.php
  database/seeders/ToolQuestionsTableSeeder.php
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/tables.css
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/calculations-table.blade.php
Labels: enhancement

#1310 Feature/lite scan/summary dropdown
  app/Http/Middleware/ChecksConditionsForSubSteps.php
  app/Http/ViewComposers/Frontend/Tool/NavbarComposer.php
  resources/views/cooperation/frontend/layouts/parts/navbar.blade.php
  resources/views/cooperation/sub-step-templates/template-summary/show.blade.php
Labels: enhancement, bugfix

#1292 Feature/lite scan/sub step mapping
  app/Console/Commands/Upgrade/LiteScan/DoUpgrade.php
  app/Console/Commands/Upgrade/LiteScan/MapQuickToLite.php
  app/Console/Commands/Upgrade/LiteScan/TriggerSaveForAllCompletedSubSteps.php
Labels: enhancement

#1306 Feature/lite scan/undefined variable
  app/Jobs/CompleteRelatedSubStep.php
Labels: awaiting approval, bugfix

#1307 Feature/lite scan/undefined index
  app/Http/Controllers/Cooperation/Tool/QuestionnaireController.php
Labels: awaiting approval, bugfix

#1309 Different recalc and woonplan logic.
  app/Http/Controllers/Cooperation/Frontend/Tool/SimpleScan/MyPlanController.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
  app/Http/Middleware/EnsureQuickScanCompleted.php
  app/Models/Building.php
  app/Models/Scan.php
  app/Services/Models/BuildingService.php
  app/Services/WoonplanService.php
  public/css/admin/app.css
  public/css/frontend/app.css
  public/icons/house-green.svg
  public/mix-manifest.json
  resources/css/shared/components/icons.css
  resources/icons/house-green.svg
  resources/views/cooperation/frontend/layouts/parts/sub-nav.blade.php
Labels: awaiting approval

#1308 Feature/lite scan/measure cache
  app/Helpers/Cache/Account.php
  app/Helpers/Cache/BaseCache.php
  app/Helpers/Cache/Building.php
  app/Helpers/Cache/Calculator.php
  app/Helpers/Cache/Cooperation.php
  app/Helpers/Cache/InputSource.php
  app/Helpers/Cache/Interest.php
  app/Helpers/Cache/Role.php
  app/Helpers/Cache/Status.php
  app/Helpers/Cache/Step.php
  app/Helpers/Cache/Translation.php
  app/Observers/MeasureApplicationObserver.php
  app/Providers/WoningdossierServiceProvider.php
  app/Traits/HasShortTrait.php
Labels: enhancement, awaiting approval

#1311 Feature/lite scan/calc explain/example building
  app/Services/Models/BuildingService.php
Labels: enhancement

#1314 Use correct exception type
  app/Services/DiscordNotifier.php
Labels: bugfix

#1068 Feature/api/coach linking
  app/Events/ParticipantAddedEvent.php
  app/Events/PrivateMessageReceiverEvent.php
  app/Helpers/Hoomdossier.php
  app/Http/Controllers/Api/V1/BuildingCoachStatusController.php
  app/Http/Controllers/Api/V1/Resources/Schemas/StoreBuildingCoachStatusRequest.php
  app/Http/Controllers/Api/V1/Resources/Schemas/StoreRegisterRequest.php
  app/Http/Controllers/Cooperation/Admin/BuildingController.php
  app/Http/Controllers/Cooperation/Admin/Cooperation/UserController.php
  app/Http/Controllers/Cooperation/Messages/ParticipantController.php
  app/Http/Requests/Api/V1/Cooperation/BuildingCoachStatusFormRequest.php
  app/Http/Requests/Api/V1/Cooperation/RegisterFormRequest.php
  app/Http/Requests/Cooperation/Admin/BuildingFormRequest.php
  app/Listeners/ParticipantAddedListener.php
  app/Listeners/PrivateMessageReceiverListener.php
  app/Models/User.php
  app/Observers/PrivateMessageObserver.php
  app/Services/PrivateMessageService.php
  app/Services/PrivateMessageViewService.php
  database/factories/UserFactory.php
  resources/lang/nl/users.php
  resources/lang/nl/validation.php
  resources/views/cooperation/admin/buildings/edit.blade.php
  resources/views/cooperation/admin/buildings/show.blade.php
  routes/api.php
  tests/Feature/app/Http/Controllers/Api/BuildingCoachStatusControllerTest.php
Labels: awaiting approval

#1312 We can't eager load roles by default
  app/Models/User.php
  resources/views/cooperation/admin/choose-roles.blade.php
  resources/views/cooperation/admin/layouts/navbar/role-switcher.blade.php
Labels: accepted, bugfix

#1297 Feature/step logic fixes
  app/Helpers/StepHelper.php
  app/Http/Controllers/Cooperation/Frontend/Tool/QuickScan/MyPlanController.php
  app/Http/Middleware/EnsureQuickScanCompleted.php
  app/Models/Building.php
  app/Services/Scans/ScanFlowService.php
Labels: awaiting approval, bugfix

#1303 Hide sliders for now
  resources/views/livewire/cooperation/frontend/tool/quick-scan/my-plan/form.blade.php
Labels: enhancement
