Repository Ecodenl/Woningdossier, pull requests merged in 2022-09, with the labels that each got.

#1077 Feature/evaluate answer options
  app/Helpers/Conditions/ConditionEvaluator.php
  app/Helpers/QuestionValues/BuildingType.php
  app/Helpers/QuestionValues/QuestionValue.php
  app/Models/ToolQuestion.php
  app/Models/ToolQuestionCustomValue.php
  app/Models/ToolQuestionValuable.php
  app/Services/ToolQuestionService.php
  database/migrations/2021_07_13_122518_create_tool_question_valuables_table.php
  database/migrations/2021_07_15_111313_create_tool_question_custom_values_table.php
  database/migrations/2022_08_24_120348_add_conditions_column_to_multiple_tables.php
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolQuestionsTableSeeder.php
  docs/code-business-logic/condition-evaluator.md
  public/icons/heat-pump-none.svg
  resources/icons/heat-pump-none.svg
  resources/views/cooperation/tool-question-type-templates/radio/show.blade.php
  tests/Unit/app/Console/Commands/AddMasterInputSourceTest.php
Labels: enhancement

#1088 Add other questions to expert scan
  database/seeds/SubSteppablesTableSeeder.php
Labels: enhancement

#1074 Fix alpine select in expert
  app/Http/Controllers/Cooperation/Tool/SolarPanelsController.php
  app/Http/Requests/Cooperation/Tool/SolarPanelFormRequest.php
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/views/cooperation/tool/solar-panels/index.blade.php
Labels: ready to be approved, bugfix

#1090 Fix conditions
  database/seeds/SubSteppablesTableSeeder.php
Labels: bugfix

#1092 Fix expert scan bugs
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Models/SubSteppable.php
  app/Policies/ToolQuestionPolicy.php
  public/js/app.js
  public/mix-manifest.json
  resources/js/alpine-scripts/alpine-select.js
  resources/views/cooperation/frontend/layouts/components/alpine-select.blade.php
  resources/views/cooperation/frontend/tool/expert-scan/parts/tool-label.blade.php
  resources/views/cooperation/frontend/tool/expert-scan/parts/tool-question.blade.php
  resources/views/cooperation/tool-question-type-templates/dropdown/show.blade.php
  resources/views/cooperation/tool-question-type-templates/multi-dropdown/show.blade.php
Labels: bugfix

#1093 Use JSON_CONTAINS instead of LIKE
  app/Services/ToolQuestionService.php
Labels: bugfix

#1078 Feature/calculation alerts
  app/Calculations/HeatPump.php
  app/Console/Commands/Upgrade/HeatPump/DoUpgrade.php
  app/Console/Commands/Upgrade/HeatPump/ReseedElementValues.php
  app/Helpers/Conditions/ConditionEvaluator.php
  app/Helpers/Conditions/Evaluators/BuildingType.php
  app/Helpers/Conditions/Evaluators/InsulationCalculation.php
  app/Helpers/Conditions/Evaluators/ShouldEvaluate.php
  app/Helpers/Conditions/Evaluators/SpecificExampleBuilding.php
  app/Http/Livewire/Cooperation/Frontend/Layouts/Parts/Alerts.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Http/ViewComposers/Frontend/Tool/NavbarComposer.php
  app/Models/Alert.php
  app/Models/ElementValue.php
  database/migrations/2022_08_22_141925_create_alerts_table.php
  database/seeds/AlertsTableSeeder.php
  database/seeds/HeatPumpCharacteristicsTableSeeder.php
  docs/code-business-logic/condition-evaluator.md
  public/js/app.js
  resources/js/alpine-scripts/dropdown.js
  resources/lang/nl/cooperation/frontend/layouts.php
  resources/views/cooperation/frontend/layouts/parts/navbar.blade.php
  resources/views/cooperation/frontend/tool/quick-scan/index.blade.php
  resources/views/livewire/cooperation/frontend/layouts/parts/alerts.blade.php
Labels: enhancement

#1095 Feature/heat pump/expert scan/livewire dom bug
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Http/Middleware/CheckForMaintenanceMode.php
Labels: bugfix

#1097 Feature/heat pump/styling
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Buttons.php
  resources/views/cooperation/frontend/layouts/tool.blade.php
  resources/views/cooperation/frontend/tool/expert-scan/parts/tool-label.blade.php
  resources/views/livewire/cooperation/frontend/tool/expert-scan/buttons.blade.php
  resources/views/livewire/cooperation/frontend/tool/expert-scan/form.blade.php
  resources/views/livewire/cooperation/frontend/tool/expert-scan/sub-steppable.blade.php
Labels: enhancement

#1094 Heat-pump calculation results
  app/Calculations/Calculator.php
  app/Calculations/HeatPump.php
  app/Calculations/Heater.php
  app/Calculations/HighEfficiencyBoiler.php
  app/Console/Commands/Upgrade/HeatPump/SeedAll.php
  app/Helpers/Conditions/Clause.php
  app/Helpers/Conditions/ConditionEvaluator.php
  app/Helpers/Conditions/Evaluators/BuildingType.php
  app/Helpers/Conditions/Evaluators/InsulationAdvice.php
  app/Helpers/Conditions/Evaluators/InsulationCalculation.php
  app/Helpers/Conditions/Evaluators/InsulationScore.php
  app/Helpers/Conditions/Evaluators/ShouldEvaluate.php
  app/Helpers/Conditions/Evaluators/SpecificExampleBuilding.php
  app/Helpers/Cooperation/Tool/HighEfficiencyBoilerHelper.php
  app/Http/Livewire/Cooperation/Frontend/Layouts/Parts/Alerts.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Models/ToolCalculationResult.php
  database/migrations/2022_09_02_163615_create_tool_calculation_results_table.php
  database/seeds/AlertsTableSeeder.php
  database/seeds/HeatPumpCharacteristicsTableSeeder.php
  database/seeds/KeyFigureHeatPumpCoveragesTableSeeder.php
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolCalculationResultsTableSeeder.php
  database/seeds/ToolLabelsTableSeeder.php
  database/seeds/ToolQuestionsTableSeeder.php
  docs/code-business-logic/condition-evaluator.md
  docs/the-mighty-book-of-decision-making.md
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/form.css
  resources/views/cooperation/frontend/tool/expert-scan/parts/tool-calculation-result.blade.php
  resources/views/cooperation/frontend/tool/expert-scan/parts/tool-label.blade.php
  resources/views/cooperation/frontend/tool/expert-scan/parts/tool-question.blade.php
  resources/views/cooperation/tool-question-type-templates/multi-dropdown/show.blade.php
  resources/views/livewire/cooperation/frontend/tool/expert-scan/sub-steppable.blade.php
Labels: enhancement, bugfix

#1096 Feature/heat pump/deprecate old steps
  app/Calculations/Calculator.php
  app/Calculations/Heater.php
  app/Calculations/HighEfficiencyBoiler.php
  app/Helpers/Conditions/Evaluators/HrBoilerAdvice.php
  app/Helpers/Conditions/Evaluators/InsulationAdvice.php
  app/Helpers/Conditions/Evaluators/InsulationScore.php
  app/Helpers/Conditions/Evaluators/SunBoilerPerformance.php
  app/Http/Controllers/Cooperation/Frontend/Tool/ExpertScanController.php
  app/Http/Controllers/Cooperation/Tool/HeatPumpController.php
  app/Http/Controllers/Cooperation/Tool/HeaterController.php
  app/Http/Controllers/Cooperation/Tool/HighEfficiencyBoilerController.php
  app/Http/Livewire/Cooperation/Frontend/Layouts/Parts/Alerts.php
  app/Http/Requests/Cooperation/Tool/HeaterFormRequest.php
  app/Http/Requests/Cooperation/Tool/HighEfficiencyBoilerFormRequest.php
  app/Traits/HasDynamicAnswers.php
  database/seeds/AlertsTableSeeder.php
  public/images/icons/verwarming.png
  resources/views/cooperation/frontend/layouts/parts/navbar.blade.php
  resources/views/cooperation/frontend/layouts/tool.blade.php
  resources/views/livewire/cooperation/frontend/tool/quick-scan/my-plan/form.blade.php
  routes/web.php
Labels: enhancement

#1098 Feature/heat pump/my plan measures
  app/Calculations/HeatPump.php
  app/Calculations/Heater.php
  app/Console/Commands/Tool/RecalculateForUser.php
  app/Console/Commands/Upgrade/HeatPump/DoUpgrade.php
  app/Console/Commands/Upgrade/HeatPump/SeedAll.php
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
  app/Helpers/Conditions/Evaluators/HrBoilerAdvice.php
  app/Helpers/Conditions/Evaluators/SunBoilerPerformance.php
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
  app/Helpers/Cooperation/Tool/HeaterHelper.php
  app/Helpers/Cooperation/Tool/HighEfficiencyBoilerHelper.php
  app/Helpers/Cooperation/Tool/ToolHelper.php
  app/Helpers/ToolHelper.php
  app/Helpers/ToolQuestionHelper.php
  app/Listeners/RecalculateToolForUserListener.php
  app/Models/Building.php
  app/Services/UserActionPlanAdviceService.php
  app/Traits/HasDynamicAnswers.php
  app/Traits/RetrievesAnswers.php
  database/seeds/MeasureApplicationsTableSeeder.php
  database/seeds/SubSteppablesTableSeeder.php
  database/seeds/ToolQuestionsTableSeeder.php
Labels: enhancement

#1103 Feature/heat pump/step completion logic
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
  app/Helpers/StepHelper.php
  app/Helpers/SubStepHelper.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/QuickScan/Form.php
  app/Models/CompletedStep.php
  app/Models/CompletedSubStep.php
  app/Traits/GetMyValuesTrait.php
Labels: enhancement

#1104 Feature/heat pump/conditional heat pump types
  app/Helpers/QuestionValues/BuildingType.php
  app/Helpers/QuestionValues/QuestionValue.php
  app/Helpers/QuestionValues/ShouldReturnQuestionValues.php
  app/Helpers/QuestionValues/SpecificExampleBuilding.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Services/ToolQuestionService.php
  database/seeds/AlertsTableSeeder.php
  database/seeds/ToolQuestionsTableSeeder.php
  public/js/app.js
  public/mix-manifest.json
  resources/js/alpine-scripts/alpine-select.js
  resources/js/alpine-scripts/source-select.js
  resources/views/cooperation/frontend/layouts/components/alpine-select.blade.php
  resources/views/cooperation/frontend/layouts/parts/source-select.blade.php
  resources/views/cooperation/tool-question-type-templates/checkbox-icon/show.blade.php
  resources/views/cooperation/tool-question-type-templates/dropdown/show.blade.php
  resources/views/cooperation/tool-question-type-templates/multi-dropdown/show.blade.php
  resources/views/cooperation/tool-question-type-templates/radio-icon-small/show.blade.php
  resources/views/cooperation/tool-question-type-templates/radio-icon/show.blade.php
  resources/views/cooperation/tool-question-type-templates/radio/show.blade.php
  resources/views/cooperation/tool/solar-panels/index.blade.php
Labels: enhancement, bugfix

#1105 Feature/heat pump/report structure
  app/Calculations/HeatPump.php
  app/Console/Commands/Upgrade/HeatPump/SeedAll.php
  app/Helpers/Hoomdossier.php
  app/Helpers/ToolHelper.php
  app/Helpers/ToolQuestionHelper.php
  app/Http/Controllers/Cooperation/Pdf/UserReportController.php
  app/Http/Controllers/Cooperation/Tool/SolarPanelsController.php
  app/Http/Controllers/Cooperation/Tool/WallInsulationController.php
  app/Jobs/GenerateTotalReport.php
  app/Models/Building.php
  app/Services/ContentStructureService.php
  app/Services/DumpService.php
  app/Services/ExampleBuildingService.php
  app/Services/ToolQuestionService.php
  database/seeds/HeatingAgesTableSeeder.php
  resources/views/cooperation/pdf/user-report/index.blade.php
  resources/views/cooperation/pdf/user-report/parts/measure-page/indicative-costs-and-measures.blade.php
Labels: enhancement

#1107 This requires seeding
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
Labels: bugfix

#1111 Feature/heat pump/calculation fix
  app/Console/Commands/Upgrade/HeatPump/UpdateToolQuestions.php
  app/Helpers/Cooperation/Tool/HeatPumpHelper.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Services/UserActionPlanAdviceService.php
  database/seeds/ServiceValuesTableSeeder.php
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/form.css
Labels: bugfix

#1113 Feature/heat pump/quick fixes
  app/Helpers/Conditions/ConditionEvaluator.php
  app/Helpers/Conditions/Evaluators/SunBoilerPerformance.php
Labels: bugfix

#1109 Use deprecation for ease of refactoring in the future
  app/Calculations/HeatPump.php
  app/Deprecation/ToolHelper.php
  app/Helpers/Conditions/Evaluators/HrBoilerAdvice.php
  app/Helpers/Conditions/Evaluators/SunBoilerPerformance.php
Labels: enhancement

#1110 Feature/heat pump/conditional step logic fix
  app/Helpers/StepHelper.php
  app/Helpers/SubStepHelper.php
  app/Models/SubSteppable.php
  app/Observers/CompletedSubStepObserver.php
Labels: enhancement, bugfix
