Repository Ecodenl/Woningdossier, pull requests merged in 2023-03, with the labels that each got.

#1415 Feature/subsidy/rating slider check
  app/Helpers/Str.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
  tests/Unit/app/Helpers/StrTest.php
Labels: awaiting approval, bugfix

#1402 Feature/subsidy/mapping free input
  app/Helpers/Str.php
  app/Http/Controllers/Cooperation/Admin/SuperAdmin/MunicipalityController.php
  app/Http/Requests/Cooperation/Admin/SuperAdmin/MunicipalityCoupleRequest.php
  resources/views/cooperation/admin/super-admin/municipalities/show.blade.php
  tests/Unit/app/Helpers/StrTest.php
Labels: enhancement, awaiting approval

#1416 Feature/subsidy/user cost csv label
  app/Helpers/Models/UserCostHelper.php
  app/Helpers/ToolHelper.php
  app/Http/Controllers/Cooperation/Pdf/UserReportController.php
  app/Jobs/GenerateToolReport.php
  app/Jobs/PdfReport.php
  app/Services/DumpService.php
  tests/Unit/app/Helpers/Models/UserCostHelperTest.php
Labels: enhancement, awaiting approval

#1419 Feature/subsidy/refresh new measure on woonplan
  app/Console/Commands/Tool/RecalculateForUser.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/Form.php
  app/Jobs/RecalculateStepForUser.php
  app/Jobs/RefreshRegulationsForUserActionPlanAdvice.php
  app/Listeners/RefreshRelatedAdvices.php
  app/Providers/AppServiceProvider.php
  app/Services/UserActionPlanAdviceService.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/form.blade.php
Labels: enhancement, awaiting approval

#1420 Move button up
  resources/views/cooperation/frontend/tool/simple-scan/my-regulations/index.blade.php
Labels: enhancement, awaiting approval

#1417 Add regulations to PDF
  app/Console/Commands/Upgrade/Subsidy/DoUpgrade.php
  app/Http/Controllers/Cooperation/Frontend/Tool/SimpleScan/MyRegulationsController.php
  app/Http/Controllers/Cooperation/Pdf/UserReportController.php
  app/Jobs/PdfReport.php
  resources/lang/nl/pdf/user-report.php
  resources/views/cooperation/pdf/user-report/parts/pages/info-page.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-regulations.blade.php
Labels: enhancement, awaiting approval

#1423 Display bag and vbjehuis municipalities in overview
  app/Console/Commands/Upgrade/Subsidy/SeedBagMunicipalityMapping.php
  app/Http/Controllers/Cooperation/Admin/SuperAdmin/MunicipalityController.php
  resources/lang/nl/cooperation/admin/super-admin/municipalities.php
  resources/views/cooperation/admin/super-admin/municipalities/index.blade.php
Labels: enhancement, awaiting approval

#1424 Feature/subsidy/bag fix
  app/Http/Controllers/Cooperation/CreateBuildingController.php
  app/Services/UserService.php
Labels: awaiting approval, bugfix

#1425 Feature/subsidy/dont force 0
  app/Helpers/DataTypes/Caster.php
  app/Helpers/ToolQuestionHelper.php
  app/Http/Livewire/Cooperation/Admin/ExampleBuildings/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/ExpertScan/SubSteppable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/Scannable.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/CalculationsTable.php
  app/Traits/HasDynamicAnswers.php
  resources/views/cooperation/frontend/layouts/parts/navbar.blade.php
  tests/Unit/app/Helpers/DataTypes/CasterTest.php
  tests/Unit/app/Helpers/NumberFormatterTest.php
Labels: enhancement, awaiting approval, bugfix

#1427 Feature/subsidy/mapping/gui change
  app/Http/Controllers/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationController.php
  app/Http/Livewire/Cooperation/Admin/SuperAdmin/CooperationPresets/CooperationPresetContents/CooperationMeasureApplications/Form.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/CustomChanges.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/Form.php
  app/Http/Requests/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationFormRequest.php
  app/Services/Models/CooperationPresetService.php
  resources/views/cooperation/admin/cooperation/cooperation-admin/cooperation-measure-applications/create.blade.php
  resources/views/cooperation/admin/cooperation/cooperation-admin/cooperation-measure-applications/edit.blade.php
  resources/views/livewire/cooperation/admin/super-admin/cooperation-presets/cooperation-preset-contents/cooperation-measure-applications/form.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/custom-changes.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/form.blade.php
Labels: enhancement, ready to be approved

#1428 Feature/subsidy/mapping/super admin/gui
  app/Http/Controllers/Cooperation/Admin/SuperAdmin/MeasureCategoryController.php
  app/Http/Livewire/Cooperation/Admin/ExampleBuildings/Form.php
  app/Http/Livewire/Cooperation/Admin/SuperAdmin/CooperationPresets/CooperationPresetContents/CooperationMeasureApplications/Form.php
  app/Http/Requests/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationFormRequest.php
  app/Http/Requests/Cooperation/Admin/SuperAdmin/MeasureApplicationFormRequest.php
  app/Http/Requests/Cooperation/Admin/SuperAdmin/MeasureCategoryRequest.php
  app/Models/MeasureCategory.php
  app/Services/Verbeterjehuis/RegulationService.php
  resources/lang/nl/cooperation/admin/shared.php
  resources/lang/nl/cooperation/admin/super-admin/measure-categories.php
  resources/lang/nl/validation.php
  resources/views/cooperation/admin/layouts/parts/sidebar/super-admin.blade.php
  resources/views/cooperation/admin/super-admin/cooperation-presets/show.blade.php
  resources/views/cooperation/admin/super-admin/measure-categories/create.blade.php
  resources/views/cooperation/admin/super-admin/measure-categories/edit.blade.php
  resources/views/cooperation/admin/super-admin/measure-categories/index.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/form.blade.php
  routes/super-admin.php
Labels: enhancement, ready to be approved

#1430 We also allow Cooperation Measures
  app/Observers/UserActionPlanAdviceObserver.php
Labels: ready to be approved, bugfix

#1431 Feature/subsidy/ensure short made
  app/Models/Building.php
  app/Models/CooperationMeasureApplication.php
  app/Models/CustomMeasureApplication.php
  app/Models/Element.php
  app/Models/Mapping.php
  app/Models/MeasureApplication.php
  app/Models/MeasureCategory.php
  app/Models/Municipality.php
  app/Models/Questionnaire.php
  app/Models/ServiceType.php
  app/Models/User.php
  app/Models/UserCost.php
Labels: awaiting approval, bugfix

#1398 Hide text help as well as pass fields
  resources/views/cooperation/auth/register.blade.php
Labels: awaiting approval, bugfix

#1400 Feature/eb confirm delete
  app/Http/Controllers/Cooperation/Admin/ExampleBuildingController.php
  app/Http/Livewire/Cooperation/Admin/ExampleBuildings/Form.php
  resources/lang/nl/cooperation/admin/example-buildings.php
  resources/lang/nl/cooperation/admin/super-admin/clients/personal-access-tokens.php
  resources/views/cooperation/admin/example-buildings/index.blade.php
  resources/views/cooperation/admin/super-admin/clients/personal-access-tokens/index.blade.php
Labels: enhancement, awaiting approval, bugfix

#1404 Fix route exception
  routes/web.php
Labels: awaiting approval, bugfix

#1397 Improved regex for house number extension
  app/Http/Requests/Api/V1/Cooperation/RegisterFormRequest.php
  app/Rules/Api/V1/HouseNumberExtension.php
  app/Rules/HouseNumberExtension.php
  tests/Unit/app/Rules/HouseNumberExtensionTest.php
Labels: awaiting approval, bugfix

#1396 Safari CSS for disabled inputs
  public/css/admin/app.css
  public/css/admin/datatables/dataTables.bootstrap.min.css
  public/css/admin/datatables/responsive.bootstrap.min.css
  public/css/admin/datatables/responsive.dataTables.min.css
  public/css/frontend/app.css
  public/css/pdf.css
  public/js/app.js
  public/js/are-you-sure.js
  public/js/datatables.js
  public/js/hoomdossier.js
  public/js/select2.js
  public/mix-manifest.json
  resources/css/frontend/components/form.css
Labels: awaiting approval, bugfix

#1421 Fix exception of empty string
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyPlan/Form.php
Labels: awaiting approval, bugfix

#1385 Finally fixed checksum exception
  app/Helpers/NumberFormatter.php
  tests/Unit/app/Helpers/NumberFormatterTest.php
Labels: awaiting approval, bugfix

#1434 Ensure we don't throw useless exceptions because of empty data
  app/Listeners/SuccessFullLoginListener.php
  app/Providers/AppServiceProvider.php
  app/Services/BuildingAddressService.php
  app/Services/Lvbag/BagService.php
  app/Services/Lvbag/Payloads/AddressExpanded.php
  app/Services/Lvbag/Payloads/City.php
  database/factories/BuildingElementFactory.php
  database/factories/BuildingHeaterFactory.php
  database/factories/BuildingVentilationFactory.php
  database/factories/ClientFactory.php
  database/factories/ElementFactory.php
  database/factories/ElementValueFactory.php
  database/factories/InputSourceFactory.php
  database/factories/InterestFactory.php
  database/factories/PvPanelOrientationFactory.php
  database/factories/QuestionFactory.php
  database/factories/ServiceTypeFactory.php
  database/factories/ToolQuestionFactory.php
  database/factories/UserFactory.php
  tests/Feature/app/Http/Controllers/Cooperation/Auth/AuthenticatedSessionControllerTest.php
  tests/MocksLvbag.php
  tests/Unit/app/Services/BuildingAddressServiceTest.php
  tests/Unit/app/Services/Lvbag/BagServiceTest.php
Labels: ready to be approved, bugfix

#1432 Feature/cleanup lite scan regulations commands
  app/Console/Commands/CheckForDuplicates.php
  app/Console/Commands/CopyBuildingData.php
  app/Console/Commands/MigrateRivierenlandToVrijstad.php
  app/Console/Commands/MigrateUser.php
  app/Console/Commands/TestMails.php
  app/Console/Commands/Upgrade/LiteScan/ChangeTranslations.php
  app/Console/Commands/Upgrade/LiteScan/ConvertQuestionnaireStepsToPivot.php
  app/Console/Commands/Upgrade/LiteScan/DeleteCompletedStep.php
  app/Console/Commands/Upgrade/LiteScan/DoUpgrade.php
  app/Console/Commands/Upgrade/LiteScan/GiveCooperationDefaultScans.php
  app/Console/Commands/Upgrade/LiteScan/MapQuickToLite.php
  app/Console/Commands/Upgrade/LiteScan/RemoveActionPlanReport.php
  app/Console/Commands/Upgrade/LiteScan/TranslationUpdate.php
  app/Console/Commands/Upgrade/LiteScan/UpdateCooperationMeasures.php
  app/Console/Commands/Upgrade/Subsidy/DeleteOldMeasureCategories.php
  app/Console/Commands/Upgrade/Subsidy/DoUpgrade.php
  app/Console/Commands/Upgrade/Subsidy/FixContractType.php
  app/Console/Commands/Upgrade/Subsidy/SeedBagMunicipalityMapping.php
  app/Console/Commands/Upgrade/Subsidy/SeedMeasureCategoryMapping.php
Labels: v4.2.1

#1433 Feature/doc update
  docs/api/api.md
  docs/code-business-logic/building-address-service.md
  docs/code-logic/custom-user-resolver.md
  docs/code-logic/jobs.md
  docs/code-logic/middleware.md
  docs/code-logic/session-handling.md
  docs/count-help-modals.md
  docs/readme.md
  docs/sql/procedure.md
Labels: v4.2.1

#1387 Feature/measure fix
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/clickables.css
  resources/css/frontend/components/items.css
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/form.blade.php
Labels: awaiting approval, bugfix

#1422 Allow files of type webp
  config/mediable.php
Labels: accepted, awaiting approval, bugfix

#1438 Feature/cooperation delete issue
  app/Console/Commands/Deploys/FixMeasureCommand.php
  app/Console/Commands/RunDeploy.php
  app/Http/Controllers/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationController.php
  app/Jobs/HandleCooperationMeasureApplicationDeletion.php
  app/Models/CooperationMeasureApplication.php
  app/Models/UserActionPlanAdvice.php
  app/Services/Verbeterjehuis/Payloads/Search.php
  database/factories/CooperationMeasureApplicationFactory.php
  database/factories/MeasureCategoryFactory.php
  database/factories/UserActionPlanAdviceFactory.php
  database/factories/UserFactory.php
  database/migrations/2014_11_02_060000_create_user_action_plan_advices_table.php
  database/migrations/2018_11_26_092056_add_input_source_id_to_user_action_plan_advices.php
  database/migrations/2019_04_03_085709_costs_decimal_length_to_18_comma_2_to_user_action_plan_advices.php
  database/migrations/2020_01_07_144303_remove_crack_sealing_measure_from_user_action_plan_advices_table_on_step_4.php
  database/migrations/2021_08_09_122304_change_measure_application_id_on_user_action_plan_advices_table.php
  database/migrations/2021_08_25_130924_add_category_column_on_user_action_plan_advices_table.php
  database/migrations/2021_08_25_164002_add_visible_column_to_user_action_plan_advices_table.php
  database/migrations/2023_01_23_135346_add_various_columns_to_user_action_plan_advices_table.php
  docs/troubleshooting.md
  tests/Feature/app/Http/Controllers/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationControllerTest.php
Labels: accepted, bugfix, v4.2.2

#1442 Add econobis wildcard to cooperations table
  app/Console/Commands/Deploys/FixMeasureCommand.php
  app/Console/Commands/RunDeploy.php
  app/Http/Controllers/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationController.php
  app/Http/Controllers/Cooperation/Admin/SuperAdmin/Cooperation/CooperationController.php
  app/Http/Requests/Cooperation/Admin/SuperAdmin/CooperationRequest.php
  app/Jobs/HandleCooperationMeasureApplicationDeletion.php
  app/Models/Cooperation.php
  app/Models/CooperationMeasureApplication.php
  app/Models/UserActionPlanAdvice.php
  app/Services/Verbeterjehuis/Payloads/Search.php
  config/mediable.php
  database/factories/CooperationMeasureApplicationFactory.php
  database/factories/MeasureCategoryFactory.php
  database/factories/UserActionPlanAdviceFactory.php
  database/factories/UserFactory.php
  database/migrations/2014_11_01_041500_add_cooperations_table.php
  database/migrations/2014_11_02_060000_create_user_action_plan_advices_table.php
  database/migrations/2018_11_26_092056_add_input_source_id_to_user_action_plan_advices.php
  database/migrations/2019_03_12_162245_add_website_url_to_cooperations_table.php
  database/migrations/2019_04_03_085709_costs_decimal_length_to_18_comma_2_to_user_action_plan_advices.php
  database/migrations/2019_10_01_150409_add_cooperation_email_to_cooperations_table.php
  database/migrations/2020_01_07_144303_remove_crack_sealing_measure_from_user_action_plan_advices_table_on_step_4.php
  database/migrations/2021_08_09_122304_change_measure_application_id_on_user_action_plan_advices_table.php
  database/migrations/2021_08_25_130924_add_category_column_on_user_action_plan_advices_table.php
  database/migrations/2021_08_25_164002_add_visible_column_to_user_action_plan_advices_table.php
  database/migrations/2023_01_23_135346_add_various_columns_to_user_action_plan_advices_table.php
  database/migrations/2023_03_20_144218_add_econobis_wildcard_column_to_cooperations_table.php
  docs/troubleshooting.md
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/clickables.css
  resources/css/frontend/components/items.css
  resources/lang/nl/cooperation/admin/super-admin/cooperations.php
  resources/lang/nl/validation.php
  resources/views/cooperation/admin/super-admin/cooperations/create.blade.php
  resources/views/cooperation/admin/super-admin/cooperations/edit.blade.php
  resources/views/cooperation/admin/super-admin/cooperations/index.blade.php
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-plan/form.blade.php
  routes/super-admin.php
  tests/Feature/app/Http/Controllers/Cooperation/Admin/Cooperation/CooperationAdmin/CooperationMeasureApplicationControllerTest.php
Labels: enhancement, ready to be approved

#1443 Add api key field
  app/Http/Controllers/Cooperation/Admin/SuperAdmin/Cooperation/CooperationController.php
  app/Http/Requests/Cooperation/Admin/SuperAdmin/CooperationRequest.php
  app/Models/Cooperation.php
  database/migrations/2014_11_01_041500_add_cooperations_table.php
  database/migrations/2023_03_21_084111_add_econobis_api_key_column_to_cooperations_table.php
  resources/lang/nl/cooperation/admin/super-admin/cooperations.php
  resources/lang/nl/validation.php
  resources/views/cooperation/admin/super-admin/cooperations/create.blade.php
  resources/views/cooperation/admin/super-admin/cooperations/edit.blade.php
Labels: enhancement, ready to be approved

#1436 Ensure we dispatch refreshes when a coach logs in on a user
  app/Http/Controllers/Cooperation/Admin/ToolController.php
  app/Jobs/CheckBuildingAddress.php
  app/Listeners/FillingToolForUserListener.php
  app/Listeners/ObservingToolForUserListener.php
  app/Listeners/SuccessFullLoginListener.php
  app/Providers/EventServiceProvider.php
  app/Services/Models/BuildingService.php
  tests/Feature/app/Http/Controllers/Cooperation/Admin/ToolControllerTest.php
Labels: enhancement, accepted, bugfix

#1448 Dynamic api client
  app/Console/Commands/Api/Econobis/Out/Hoomdossier/All.php
  app/Console/Commands/Api/Econobis/Out/Hoomdossier/AppointmentDate.php
  app/Console/Commands/Api/Econobis/Out/Hoomdossier/Delete.php
  app/Console/Commands/Api/Econobis/Out/Hoomdossier/PdfReport.php
  app/Console/Commands/Api/Econobis/Out/Hoomdossier/ScanStatus.php
  app/Jobs/Econobis/Out/SendAppointmentDateToEconobis.php
  app/Jobs/Econobis/Out/SendBuildingFilledInAnswersToEconobis.php
  app/Jobs/Econobis/Out/SendBuildingStatusToEconobis.php
  app/Jobs/Econobis/Out/SendScanStatusToEconobis.php
  app/Jobs/Econobis/Out/SendUserActionPlanAdvicesToEconobis.php
  app/Jobs/Econobis/Out/SendUserDeletedToEconobis.php
  app/Providers/AppServiceProvider.php
  app/Providers/EconobisServiceProvider.php
  app/Services/Econobis/Api/Client.php
  app/Services/Econobis/Api/Econobis.php
  app/Services/Econobis/Api/EconobisApi.php
  app/Services/UserService.php
  config/app.php
  config/hoomdossier.php
Labels: enhancement, awaiting approval

#1453 Feature/econobis link/send pdf after interval
  app/Console/Commands/Api/Econobis/Out/Hoomdossier/PdfReport.php
  app/Console/Kernel.php
  app/Jobs/Econobis/Out/CallsEconobisApi.php
  app/Jobs/Econobis/Out/SendPdfReportToEconobis.php
  app/Models/FileStorage.php
  app/Models/InputSource.php
  app/Services/Econobis/Payloads/PdfReportPayload.php
  app/Traits/GetMyValuesTrait.php
  config/hoomdossier.php
  database/migrations/2019_05_09_102112_create_file_storages_table.php
  database/migrations/2019_09_03_112028_add_input_source_id_to_file_storages_table.php
  database/migrations/2019_09_03_140824_drop_content_type_from_file_storages_table.php
  database/migrations/2019_09_03_150817_add_building_id_to_file_storages_table.php
  database/migrations/2020_01_20_150924_add_questionnaire_id_column_to_file_storages_table.php
Labels: enhancement, awaiting approval

#1454 Prevent overlapping when the job takes too long
  app/Jobs/Econobis/Out/SendPdfReportToEconobis.php
Labels: enhancement
