Repository Ecodenl/Woningdossier, pull requests merged in 2023-04, with the labels that each got.

#1450 Alternate fix for Safari so it doesn't ruin other browsers
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/items.css
  resources/views/cooperation/frontend/layouts/app.blade.php
Labels: awaiting approval, bugfix

#1444 Feature/last refresh
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/MyRegulations.php
  app/Jobs/RefreshRegulationsForBuildingUser.php
  app/Jobs/RefreshRegulationsForUserActionPlanAdvice.php
  app/Observers/ToolQuestionAnswer/BuildingContractType.php
  app/Observers/UserActionPlanAdviceObserver.php
  app/Services/UserActionPlanAdviceService.php
  docs/the-mighty-book-of-decision-making.md
  resources/views/livewire/cooperation/frontend/tool/simple-scan/my-regulations.blade.php
Labels: awaiting approval, bugfix

#1446 Feature/vbjehuis empty search exception
  app/Console/Commands/Api/Verbeterjehuis/Mappings/SyncTargetGroups.php
  app/Providers/AppServiceProvider.php
  app/Services/Verbeterjehuis/Client.php
  app/Services/Verbeterjehuis/RegulationService.php
  app/Services/Verbeterjehuis/Resources/Regulation.php
Labels: bug, awaiting approval

#1458 Instead of showing nothing, show "Gemeente onbekend."
  resources/lang/nl/cooperation/admin/buildings.php
  resources/views/cooperation/admin/buildings/edit.blade.php
  resources/views/cooperation/admin/buildings/show.blade.php
Labels: awaiting approval

#1459 Added manuals.
  resources/views/cooperation/admin/layouts/parts/sidebar/manuals-li.blade.php
  resources/views/cooperation/admin/layouts/sidebar-menu.blade.php
Labels: awaiting approval
