Repository Ecodenl/Woningdossier, pull requests merged in 2023-07, with the labels that each got.

#1531 Feature/quiet output
  app/Console/Commands/Api/Verbeterjehuis/Mappings/SyncMeasures.php
  app/Console/Commands/Api/Verbeterjehuis/Mappings/SyncTargetGroups.php
  app/Jobs/CheckBuildingAddress.php
  app/Jobs/GenerateToolReport.php
Labels: cleanup, awaiting approval

#1529 forCooperation bugfix
  routes/auth.php
Labels: awaiting approval, bugfix

#1530 Undefined index fix
  app/Http/Livewire/Cooperation/Admin/SuperAdmin/Cooperations/Form.php
Labels: awaiting approval, bugfix

#1528 Ensure we don't make the custom dropdown look disabled
  public/css/frontend/app.css
  public/mix-manifest.json
  resources/css/frontend/components/form.css
Labels: awaiting approval, bugfix

#1532 Ensure we can actually provide a cooperation
  app/Console/Commands/Macros/UpdateContactIds.php
Labels: enhancement, awaiting approval

#1526 Fixes regarding empty string values
  app/Helpers/NumberFormatter.php
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/CustomMeasureForm.php
  tests/Unit/app/Helpers/NumberFormatterTest.php
Labels: awaiting approval, bugfix

#1533 Undefined index exception
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/CustomMeasureForm.php
Labels: awaiting approval, bugfix

#1473 Feature/remove heat source water default
  app/Helpers/RoleHelper.php
  database/seeders/ToolQuestionsTableSeeder.php
Labels: enhancement, awaiting approval

#1534 Explicit query.
  app/Http/Livewire/Cooperation/Frontend/Tool/SimpleScan/Form.php
Labels: bugfix

#1484 Larger panel heading
  public/css/admin/app.css
  public/mix-manifest.json
  resources/sass/admin/views/cooperation/tool/_defaults.scss
Labels: enhancement, awaiting approval

#1475 Command to clean up expired files.
  app/Console/Commands/CleanupExpiredFileStorages.php
  app/Console/Kernel.php
Labels: enhancement, awaiting approval

#1516 Phone number can be undefined
  app/Services/UserService.php
Labels: awaiting approval, bugfix
